# Русские заголовки Safeguard'ов CIS Control 6 для отчётов census framework.
# Заголовки перефразированы (не текст CIS); нормативная формулировка CIS Controls
# (© Center for Internet Security) защищена авторским правом и здесь не воспроизводится.
# Ключи — номера Safeguard'ов (строки, т.к. точка в TOML — разделитель), как в controls.toml.

["6.1"]
title = "Установлен процесс предоставления доступа"

["6.2"]
title = "Установлен процесс отзыва доступа"

["6.7"]
title = "Централизация управления доступом через службу каталога/SSO"

["6.8"]
title = "Ролевая модель управления доступом (RBAC)"
